default: &default
  adapter: postgresql
  encoding: unicode
  username: app_user
  password: app_password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: project_development

test:
  <<: *default
  database: project_test

production:
  <<: *default
  database: project_production
  username: app_user
  password: <%= ENV['app_password'] %>